### ISSUE TITLE
Pls add 

### ISSUE THREAD

**Issue by LogiBear11** [axmyo/Cow-s-Helper#6]
if (check) return;
	if(target.id === message.author.id) return message.reply('Why you want to ban yourself?!', { allowedMentions: { repliedUser: false } });
	if(target.id === client.user.id) return message.reply('How dare you!', { allowedMentions: { repliedUser: false } });
        if(target.roles.cache.has("742803994816020503")) return message.reply("No banning mods please")});
        if(target.roles.cache.has("IM BANNED SO I CANT GET IT ATM")) return message.reply("No banning trial mods please")});

**Comment by axmyo** [comment]
:hmm:, yea it would be nice to actually prevent mods banning themself, you can just create a pull request asnd I will approve it.

**Comment by LogiBear11** [comment]
> :hmm:, yea it would be nice to actually prevent mods banning themself, you can just create a pull request asnd I will approve it.

Righto! Will do once I work out how to do it

**Comment by SteakFisher** [comment]
Fork the repository, edit the code in the fork however you want, and then an option to contribute will pop up at the top, and it'll automatically open a pull request here
